#!/usr/bin/env bash

# Copy (as hard links) the dot files to the home directory
cp -l .bashrc    "$HOME"
cp -l .gitconfig "$HOME"
cp -l .inputrc   "$HOME"
cp -l .vimrc     "$HOME"

. ubuntu-setup-packages.sh
