#!/usr/bin/env bash

# Copy (as hard links) the dot files to the home directory
cp -l .bashrc    "$HOME"
cp -l .gitconfig "$HOME"
cp -l .inputrc   "$HOME"
cp -l .vimrc     "$HOME"

# Install the apt packages
. install-apt-packages.sh

# Setup preferences
. setup-preferences.sh

# Copy binary (and other executable) files
. copy-bin.sh
